
# Temporary setup
spring.datasource.url=jdbc:mysql://localhost:3306/testing_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=db_user
spring.datasource.password=password

# See how JPA builds database
spring.jpa.hibernate.ddl-auto=create-drop

# 256-bit JWT secret (generated at https://jwtsecrets.com/), lasting 4 hours
jwt.secret=ec46010344b2c733abb04948f747f4f9e9473ed06d3743857e7ccdab1f05565d
jwt.expiration-ms=14400000